### ISSUE TITLE
Update wiki page on Sugar Labs

### ISSUE THREAD

**Issue by justwheel** [tcreeds/PyCut#13]
# Summary

The [wiki page information](https://wiki.sugarlabs.org/go/Activities/PyCut) for PyCut will need to be updated with current information about the development of the project this semester.

# Analysis

The wiki page is the "front door" that people in the Sugar community will see the activity on. It will be appropriate for the team to update the following content:

* **Description**: An updated description should be provided that adds information about some of the game's new functionality.
* **Current status**: Is there a targeted release number (v2.0)? What kind of things are being worked on the project currently? This is the place to give an update about what's happening in the project now.
* **To-do**: Some of these things can probably be moved from "To-Do" into subcategories of the _Description_ section. They will also need some editing to make sure it accurately describes how it is implemented in the actual game code now.
* **Contributors**: Each team member should add their name and an internal link to their user page on the Sugar Labs wiki (adding content to your user page is also a good idea). You can see either mine or @tcreeds's entry as an example.

# Implementation

1. Review existing content
2. See what needs to be updated
3. Rewrite content to be accurate for the revised game
4. Edit the wiki page with the new content

**Comment by adf5051** [comment]
Wiki has been updated
