### ISSUE TITLE
Play Game - Suggest Paths Forward

### ISSUE THREAD

**Issue by adf5051** [tcreeds/PyCut#2]
@tcreeds @adf5051 @PatrickGormley

We should all get the game running and play it.
Then, we can use this issue to keep track of and discuss possible paths forward.

**Comment by adf5051** [comment]
I think we could add difficulty modes. We can just add more toppings at a minimum. 

We could also try and make a fractions game where you cut the pizza up

**Comment by tcreeds** [comment]
I think adding different difficulties is a good way to get started. It'll let us get familiar with the codebase without requiring too much architecting of new systems.

**Comment by PatrickGormley** [comment]
Finally documented some ideas: 

To make this game more math based and to implement fractions we can add in fractions of toppings. Each topping, say cheese, would have several options: 1, ½, ¼. With this the clues could be more along the lines of “I would like half as much cheese” or “I want pizza with three times the cheese as other toppings”. Implementing different fractions and relationships between amounts of toppings will add some math component. The greatest difficulty with this would be to program a way to generate the clues for fractional relationships, but I’m confident we could come up with a clever solution.

If  we have time and want to we could also implement a cost for each topping and have a total budget for the pizza as well. This could be either higher levels or another game mode. Easy being the original game,  medium with the fractions added, and hard being with the money. With the time we have left combined with the fact that this is a development environment we are not familiar with this would be a major stretch, but it would be nice to document this in a future idea section of the wiki/Git maybe for future classes.

**Comment by adf5051** [comment]
I think maybe taking this idea and keeping the original game as a mode and this fractions add on as a mode would be good too.

**Comment by adf5051** [comment]
We have moved forward with our advanced difficulty mode. This incorporates a group of people trying to order a pizza together introducing fractions to the gameplay. Closing...
