### ISSUE TITLE
Wiki Link points to the Upstream

### ISSUE THREAD

**Issue by adf5051** [tcreeds/PyCut#3]
The Readme wiki link points back to the original upstream repo. Maybe we should alter this to be our own.

**Comment by justwheel** [comment]
It might also be worth considering to improve the upstream documentation. If the goal for the end of the project is to merge everything back upstream for cutting a new release of the game, it would be beneficial to improve the "upstream docs". You all should have the ability to make edits to that wiki as well.

Additionally, the same thing goes for [Sugar Labs PyCut wiki page](https://wiki.sugarlabs.org/go/Activities/PyCut).

**Comment by adf5051** [comment]
closing, making an issue for updating the upstream wikis as that seems the best route forward
