### ISSUE TITLE
Determine the Logic for Fractions

### ISSUE THREAD

**Issue by adf5051** [tcreeds/PyCut#6]
Determine the Logic and State Machine for Fractions.

This is the guts of the fractions difficulty. No UI just the logic.

**Comment by PatrickGormley** [comment]
To-do for this: 
1. Post pseudo code 
2. Give out clues over time
3. Clues relate to inputted guesses

**Comment by adf5051** [comment]
closing, psuedo code is in a branch and the real logic is being coded in now.
